<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Destination;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $adventure = Category::where('slug', 'adventure')->first();
        $culture = Category::where('slug', 'culture')->first();
        $food = Category::where('slug', 'food')->first();

        $destinations = [
            // ─── Adventure ───────────────────────────────────────────────
            [
                'category_id' => $adventure->id,
                'name' => 'Patagonia',
                'slug' => 'patagonia-chile',
                'location' => 'Torres del Paine, Chile',
                'description' => 'Patagonia is a sparsely populated region at the southern end of South America, shared by Argentina and Chile. The region comprises the southern section of the Andes mountains, lakes, fjords, and glaciers. The iconic Torres del Paine granite peaks rise dramatically above the landscape, creating one of the most spectacular mountain vistas on Earth. Trekkers from around the world come to experience the famous W Trek and Circuit, navigating through ancient forests of lenga beech trees, crossing suspension bridges over turquoise rivers, and camping beneath star-filled southern skies. The region is home to guanacos, condors, and pumas that roam the vast grasslands.',
                'short_description' => 'Embark on epic treks through glaciers, granite towers, and pristine wilderness in South America\'s last frontier.',
                'latitude' => -51.2538,
                'longitude' => -72.3464,
                'hero_image' => 'images/destinations/patagonia-3.jpg',
                'gallery' => [
                    'images/destinations/patagonia-1.jpg',
                    'images/destinations/patagonia-2.jpg',
                    'images/destinations/patagonia-3.jpg',
                ],
                'best_time' => 'October - April',
                'budget' => '$$$',
                'language' => 'Spanish',
                'currency' => 'Chilean Peso (CLP)',
                'travel_tips' => 'Book refugios (mountain huts) well in advance for the W Trek. Bring layers — weather changes rapidly. Wind-proof gear is essential. Park entrance fees apply.',
                'is_featured' => true,
                'is_hidden_gem' => false,
                'rating' => 4.9,
                'meta_title' => 'Patagonia Travel Guide — Trek Torres del Paine, Chile',
                'meta_description' => 'Plan your Patagonia adventure. Comprehensive guide to trekking Torres del Paine, including best trails, packing tips, and booking advice.',
            ],
            [
                'category_id' => $adventure->id,
                'name' => 'Banff National Park',
                'slug' => 'banff-national-park',
                'location' => 'Alberta, Canada',
                'description' => 'Banff National Park, established in 1885, is Canada\'s oldest national park and part of the Canadian Rocky Mountain Parks UNESCO World Heritage Site. Spanning over 6,641 square kilometers of mountainous terrain, the park is home to some of the most breathtaking alpine scenery in the world. Lake Louise, with its emerald-green waters reflecting the surrounding glaciers and mountains, is one of the most photographed lakes on Earth. The Icefields Parkway connects Banff to Jasper, offering 232 kilometers of awe-inspiring mountain vistas, ancient glaciers, and cascading waterfalls.',
                'short_description' => 'Crystal-clear alpine lakes, towering peaks, and world-class skiing in the heart of the Canadian Rockies.',
                'latitude' => 51.4968,
                'longitude' => -115.9281,
                'hero_image' => 'images/destinations/banff-3.jpg',
                'gallery' => [
                    'images/destinations/banff-1.jpg',
                    'images/destinations/banff-2.jpg',
                    'images/destinations/banff-3.jpg',
                ],
                'best_time' => 'June - September',
                'budget' => '$$',
                'language' => 'English, French',
                'currency' => 'Canadian Dollar (CAD)',
                'travel_tips' => 'Get a Parks Canada Discovery Pass for best value. Book Lake Louise parking shuttle in summer. Watch for wildlife on roads. Carry bear spray on hikes.',
                'is_featured' => true,
                'is_hidden_gem' => false,
                'rating' => 4.8,
                'meta_title' => 'Banff National Park Travel Guide — Canadian Rockies Adventure',
                'meta_description' => 'Explore Banff National Park. Guide to hiking, Lake Louise, Icefields Parkway, wildlife, and seasonal tips.',
            ],
            [
                'category_id' => $adventure->id,
                'name' => 'Queenstown',
                'slug' => 'queenstown-new-zealand',
                'location' => 'Otago, New Zealand',
                'description' => 'Nestled on the shores of Lake Wakatipu and surrounded by the Remarkables mountain range, Queenstown is widely regarded as the adventure capital of the world. This compact town packs an extraordinary range of adrenaline-pumping activities into its stunning alpine setting. From bungee jumping at the historic Kawarau Bridge — the world\'s first commercial bungee site — to jet boating through narrow canyons at breathtaking speeds, the options are limitless. In winter, four world-class ski fields transform the surrounding mountains into a paradise for snow sports enthusiasts.',
                'short_description' => 'The adventure capital of the world — bungee jumping, skydiving, and jaw-dropping alpine scenery.',
                'latitude' => -45.0312,
                'longitude' => 168.6626,
                'hero_image' => 'images/destinations/queenstown-1.jpg',
                'gallery' => [
                    'images/destinations/queenstown-1.jpg',
                    'images/destinations/queenstown-2.jpg',
                    'images/destinations/queenstown-3.jpg',
                ],
                'best_time' => 'December - February',
                'budget' => '$$',
                'language' => 'English',
                'currency' => 'New Zealand Dollar (NZD)',
                'travel_tips' => 'Book adventure activities online for discounts. The Queenstown Trail offers free scenic biking. Drive the Glenorchy Road for LOTR filming locations.',
                'is_featured' => false,
                'is_hidden_gem' => false,
                'rating' => 4.7,
                'meta_title' => 'Queenstown Travel Guide — New Zealand Adventure Capital',
                'meta_description' => 'Your guide to Queenstown, New Zealand. Best adventure activities, skiing, scenic drives, and travel tips.',
            ],
            [
                'category_id' => $adventure->id,
                'name' => 'Faroe Islands',
                'slug' => 'faroe-islands',
                'location' => 'North Atlantic, Denmark',
                'description' => 'The Faroe Islands are an archipelago of 18 volcanic islands in the North Atlantic, between Iceland and Norway. These remote islands offer some of the most dramatic and untouched landscapes in Europe — sheer sea cliffs plunging hundreds of meters into the ocean, grass-roofed villages clinging to mountainsides, and cascading waterfalls that seem to flow directly into the sea. The famous Múlafossur Waterfall in Gásadalur village drops 30 meters from a cliff edge directly into the ocean, creating one of the most iconic scenes in world travel. The village of Saksun sits in a breathtaking glacial valley with a tidal lagoon — one of the most photographed spots in the North Atlantic. Birdwatchers flock to the Vestmanna sea cliffs, home to thousands of puffins, gannets, and guillemots.',
                'short_description' => 'Remote volcanic islands with dramatic sea cliffs, grass-roofed villages, and waterfalls cascading into the ocean.',
                'latitude' => 61.8926,
                'longitude' => -6.9118,
                'hero_image' => 'images/destinations/faroe-1.jpg',
                'gallery' => [
                    'images/destinations/faroe-1.jpg',
                    'images/destinations/faroe-2.jpg',
                    'images/destinations/faroe-3.jpg',
                ],
                'best_time' => 'May - September',
                'budget' => '$$$',
                'language' => 'Faroese, Danish',
                'currency' => 'Danish Krone (DKK)',
                'travel_tips' => 'Rent a car — public transport is limited. Weather changes every 15 minutes. Pack waterproof everything. Try fermented lamb and fresh seafood.',
                'is_featured' => false,
                'is_hidden_gem' => true,
                'rating' => 4.9,
                'meta_title' => 'Faroe Islands Travel Guide — Remote North Atlantic Adventure',
                'meta_description' => 'Discover the Faroe Islands. Guide to dramatic cliffs, hidden villages, hiking trails, and travel essentials.',
            ],

            // ─── Culture ─────────────────────────────────────────────────
            [
                'category_id' => $culture->id,
                'name' => 'Kyoto',
                'slug' => 'kyoto-japan',
                'location' => 'Kansai, Japan',
                'description' => 'Kyoto served as Japan\'s capital for over a thousand years, from 794 to 1868, and remains the country\'s cultural heart. The city is home to an extraordinary 17 UNESCO World Heritage Sites, over 2,000 temples and shrines, and a living tradition of arts and crafts that stretches back centuries. Walking through the vermillion torii gates of Fushimi Inari Shrine, watching a geisha glide through the lantern-lit streets of Gion, or contemplating the perfect simplicity of a Zen rock garden — these are experiences that connect visitors to the deep spiritual and aesthetic traditions of Japan.',
                'short_description' => 'Ancient temples, bamboo forests, and geisha districts — the timeless cultural heart of Japan.',
                'latitude' => 35.0116,
                'longitude' => 135.7681,
                'hero_image' => 'images/destinations/kyoto-1.jpg',
                'gallery' => [
                    'images/destinations/kyoto-1.jpg',
                    'images/destinations/kyoto-2.jpg',
                    'images/destinations/kyoto-3.jpg',
                ],
                'best_time' => 'March - May, October - November',
                'budget' => '$$',
                'language' => 'Japanese',
                'currency' => 'Japanese Yen (JPY)',
                'travel_tips' => 'Visit Fushimi Inari at dawn to avoid crowds. Get a bus day pass for ¥700. Cherry blossom season (late March) and autumn foliage (November) are peak — book months ahead.',
                'is_featured' => true,
                'is_hidden_gem' => false,
                'rating' => 4.9,
                'meta_title' => 'Kyoto Travel Guide — Temples, Geisha & Japanese Culture',
                'meta_description' => 'Explore Kyoto, Japan. Complete guide to temples, shrines, traditional culture, cherry blossoms, and local cuisine.',
            ],
            [
                'category_id' => $culture->id,
                'name' => 'Machu Picchu',
                'slug' => 'machu-picchu-peru',
                'location' => 'Cusco Region, Peru',
                'description' => 'Perched at 2,430 meters above sea level on a mountain ridge above the Sacred Valley, Machu Picchu is the most iconic archaeological site in the Americas. Built in the 15th century under the Inca emperor Pachacuti, this extraordinary citadel was abandoned during the Spanish Conquest and remained hidden from the outside world until American explorer Hiram Bingham brought it to international attention in 1911. The site\'s sophisticated dry-stone construction, astronomical alignments, and terraced agricultural design demonstrate the remarkable engineering prowess of the Inca civilization.',
                'short_description' => 'The legendary lost city of the Incas — a mountaintop citadel of extraordinary archaeological wonder.',
                'latitude' => -13.1631,
                'longitude' => -72.5450,
                'hero_image' => 'images/destinations/machu-picchu-1.jpg',
                'gallery' => [
                    'images/destinations/machu-picchu-1.jpg',
                    'images/destinations/machu-picchu-2.jpg',
                    'images/destinations/machu-picchu-3.jpg',
                ],
                'best_time' => 'April - October',
                'budget' => '$$',
                'language' => 'Spanish, Quechua',
                'currency' => 'Peruvian Sol (PEN)',
                'travel_tips' => 'Book Inca Trail permits 6+ months ahead — only 500 people per day. Acclimatize in Cusco (3,400m) for 2-3 days first. Arrive at dawn for the best photos and fewer crowds.',
                'is_featured' => true,
                'is_hidden_gem' => false,
                'rating' => 4.9,
                'meta_title' => 'Machu Picchu Travel Guide — Inca Trail & Ancient Citadel',
                'meta_description' => 'Plan your Machu Picchu trip. Guide to the Inca Trail, permits, altitude tips, and exploring the Sacred Valley.',
            ],
            [
                'category_id' => $culture->id,
                'name' => 'Fez Medina',
                'slug' => 'fez-medina-morocco',
                'location' => 'Fez, Morocco',
                'description' => 'Fez el-Bali is the largest car-free urban area in the world and one of the best-preserved medieval cities on Earth. Founded in the 9th century, the medina contains over 9,000 alleyways — some so narrow that only a donkey can pass through. Within this labyrinthine maze lies the University of al-Qarawiyyin, founded in 859 AD and recognized by UNESCO as the oldest existing, continually operating university in the world. The Chouara Tannery, where leather has been dyed using traditional methods for nearly a thousand years, offers one of Morocco\'s most iconic visual experiences.',
                'short_description' => 'The world\'s largest car-free urban area — a living medieval labyrinth of artisans, spices, and ancient learning.',
                'latitude' => 34.0617,
                'longitude' => -4.9734,
                'hero_image' => 'images/destinations/fez-1.jpg',
                'gallery' => [
                    'images/destinations/fez-1.jpg',
                    'images/destinations/fez-2.jpg',
                    'images/destinations/fez-3.jpg',
                ],
                'best_time' => 'March - May, September - November',
                'budget' => '$',
                'language' => 'Arabic, French, Berber',
                'currency' => 'Moroccan Dirham (MAD)',
                'travel_tips' => 'Hire an official guide for your first medina visit — it\'s easy to get lost. Visit tanneries in the morning when colors are being prepared. Bargain respectfully at souks — start at 40% of asking price.',
                'is_featured' => false,
                'is_hidden_gem' => true,
                'rating' => 4.6,
                'meta_title' => 'Fez Medina Travel Guide — Morocco\'s Ancient Labyrinth',
                'meta_description' => 'Discover Fez Medina, Morocco. Guide to navigating the ancient medina, tanneries, artisan workshops, and Moroccan cuisine.',
            ],
            [
                'category_id' => $culture->id,
                'name' => 'Valletta',
                'slug' => 'valletta-malta',
                'location' => 'Malta',
                'description' => 'Valletta, the capital of Malta, is a UNESCO World Heritage Site and one of the most concentrated historic areas in the world. Built by the Knights of St. John after the Great Siege of 1565, every street in this tiny capital (measuring just 1km by 600m) is a masterpiece of Baroque architecture. St. John\'s Co-Cathedral houses Caravaggio\'s masterpiece "The Beheading of Saint John the Baptist." The city sits on a peninsula surrounded by the Grand Harbour, offering stunning views at every turn. Despite its small size, Valletta packs more history per square meter than almost any city on Earth.',
                'short_description' => 'A Baroque masterpiece — Europe\'s smallest capital packed with Knights Templar history and Mediterranean charm.',
                'latitude' => 35.8989,
                'longitude' => 14.5146,
                'hero_image' => 'images/destinations/valletta-1.jpg',
                'gallery' => [
                    'images/destinations/valletta-1.jpg',
                    'images/destinations/valletta-2.jpg',
                    'images/destinations/valletta-3.jpg',
                ],
                'best_time' => 'April - June, September - November',
                'budget' => '$$',
                'language' => 'Maltese, English',
                'currency' => 'Euro (EUR)',
                'travel_tips' => 'Walk everywhere — Valletta is tiny and best explored on foot. Visit the Upper Barrakka Gardens at noon for the cannon salute. Take a harbor cruise for the best views of the city\'s fortifications.',
                'is_featured' => false,
                'is_hidden_gem' => true,
                'rating' => 4.5,
                'meta_title' => 'Valletta Travel Guide — Malta\'s Baroque Capital',
                'meta_description' => 'Explore Valletta, Malta. Guide to Baroque architecture, Knights\' history, Mediterranean cuisine, and harbor views.',
            ],

            // ─── Food ────────────────────────────────────────────────────
            [
                'category_id' => $food->id,
                'name' => 'Bangkok Street Food',
                'slug' => 'bangkok-street-food',
                'location' => 'Bangkok, Thailand',
                'description' => 'Bangkok is widely regarded as the street food capital of the world. The city\'s sidewalks, alleyways, and floating markets transform into an endless culinary landscape where the aroma of sizzling woks, grilling satay, and fragrant curries fills the air from dawn until well past midnight. Yaowarat Road in Chinatown comes alive after dark with hundreds of vendors offering everything from crispy pork belly to flambéed seafood. Jay Fai, a legendary street cook famous for her signature crab omelette, became the first Thai street food vendor to earn a Michelin star.',
                'short_description' => 'The world\'s street food capital — legendary night markets, Michelin-starred vendors, and flavors that ignite the senses.',
                'latitude' => 13.7563,
                'longitude' => 100.5018,
                'hero_image' => 'images/destinations/bangkok-1.jpg',
                'gallery' => [
                    'images/destinations/bangkok-1.jpg',
                    'images/destinations/bangkok-2.jpg',
                    'images/destinations/bangkok-3.jpg',
                ],
                'food_dishes' => [
                    [
                        'name' => 'Pad Thai',
                        'description' => 'Thailand\'s most iconic dish — stir-fried rice noodles with shrimp, egg, bean sprouts, and crushed peanuts.',
                        'image' => 'images/food/bangkok-pad-thai.jpg',
                        'price_range' => '60–120 THB',
                    ],
                    [
                        'name' => 'Tom Yum Goong',
                        'description' => 'Intensely aromatic spicy-sour soup with tiger prawns, lemongrass, galangal, and kaffir lime leaves.',
                        'image' => 'images/food/bangkok-tom-yum.jpg',
                        'price_range' => '80–200 THB',
                    ],
                    [
                        'name' => 'Mango Sticky Rice',
                        'description' => 'Perfectly ripe golden mango served over sweet coconut milk sticky rice — Bangkok\'s most beloved dessert.',
                        'image' => 'images/food/bangkok-mango-rice.jpg',
                        'price_range' => '50–100 THB',
                    ],
                ],
                'restaurants' => [
                    [
                        'name' => 'Jay Fai',
                        'description' => 'Michelin-starred street food legend. Famous crab omelette and drunken noodles. Queue from 6am.',
                        'cuisine' => 'Thai Street Food',
                        'price_range' => '$$$',
                        'address' => '327 Maha Chai Rd, Bangkok',
                        'rating' => 4.9,
                    ],
                    [
                        'name' => 'Thip Samai',
                        'description' => 'Bangkok\'s most famous pad thai since 1966. Open only at night, and always has a line.',
                        'cuisine' => 'Pad Thai Specialist',
                        'price_range' => '$',
                        'address' => '313-315 Maha Chai Rd, Bangkok',
                        'rating' => 4.7,
                    ],
                    [
                        'name' => 'Nahm',
                        'description' => 'Award-winning fine dining exploring the depths of traditional Thai cuisine with elegant modern presentation.',
                        'cuisine' => 'Fine Thai Dining',
                        'price_range' => '$$$$',
                        'address' => 'COMO Metropolitan Hotel, Bangkok',
                        'rating' => 4.8,
                    ],
                ],
                'best_time' => 'November - February',
                'budget' => '$',
                'language' => 'Thai',
                'currency' => 'Thai Baht (THB)',
                'travel_tips' => 'Eat where locals eat — long queues = great food. Yaowarat is best after 7pm. Try pad thai, som tum, mango sticky rice, and boat noodles. Carry small bills for street vendors.',
                'is_featured' => true,
                'is_hidden_gem' => false,
                'rating' => 4.8,
                'meta_title' => 'Bangkok Street Food Guide — Night Markets & Local Eats',
                'meta_description' => 'Your guide to Bangkok street food. Best night markets, must-try dishes, food tours, and insider tips.',
            ],
            [
                'category_id' => $food->id,
                'name' => 'Bologna',
                'slug' => 'bologna-italy',
                'location' => 'Emilia-Romagna, Italy',
                'description' => 'Bologna, nicknamed "La Grassa" (The Fat One) by Italians themselves, is the undisputed culinary capital of Italy. This medieval university city in the Emilia-Romagna region is the birthplace of many of Italy\'s most beloved foods: ragù alla bolognese, tortellini, tagliatelle, mortadella, and lasagne all originated here. The city\'s food markets and portico-lined streets offer an authentic Italian culinary experience far removed from tourist traps. The Quadrilatero market district, dating back to the Middle Ages, is a sensory feast of hanging prosciutto, wheels of Parmigiano-Reggiano, and barrels of aged balsamic vinegar.',
                'short_description' => 'Italy\'s culinary capital — birthplace of ragù, tortellini, and Parmigiano-Reggiano in medieval splendor.',
                'latitude' => 44.4949,
                'longitude' => 11.3426,
                'hero_image' => 'images/destinations/bologna-1.jpg',
                'gallery' => [
                    'images/destinations/bologna-1.jpg',
                    'images/destinations/bologna-2.jpg',
                    'images/destinations/bologna-3.jpg',
                ],
                'food_dishes' => [
                    [
                        'name' => 'Tagliatelle al Ragù',
                        'description' => 'The original bolognese — handmade egg tagliatelle pasta with a rich slow-cooked meat sauce. Never spaghetti!',
                        'image' => 'images/food/bologna-tagliatelle.jpg',
                        'price_range' => '12–18 EUR',
                    ],
                    [
                        'name' => 'Tortellini in Brodo',
                        'description' => 'Tiny ring-shaped pasta filled with pork and Parmigiano, swimming in a crystal-clear Parmesan broth.',
                        'image' => 'images/food/bologna-tortellini.jpg',
                        'price_range' => '10–16 EUR',
                    ],
                    [
                        'name' => 'Mortadella di Bologna',
                        'description' => 'The original bologna — giant rose-pink pork sausage studded with pistachios, the pride of the city.',
                        'image' => 'images/food/bologna-mortadella.jpg',
                        'price_range' => '3–8 EUR (per portion)',
                    ],
                ],
                'restaurants' => [
                    [
                        'name' => 'Osteria Francescana',
                        'description' => 'Three Michelin stars and consistently ranked world\'s best restaurant by Massimo Bottura — a pilgrimage for food lovers.',
                        'cuisine' => 'Modern Italian Fine Dining',
                        'price_range' => '$$$$',
                        'address' => 'Via Stella 22, Modena (30 min from Bologna)',
                        'rating' => 5.0,
                    ],
                    [
                        'name' => 'Trattoria Anna Maria',
                        'description' => 'Bologna institution since 1987. Handmade pasta, walls covered in signed celebrity photos, and recipes unchanged for decades.',
                        'cuisine' => 'Traditional Bolognese',
                        'price_range' => '$$',
                        'address' => 'Via Belle Arti 17/A, Bologna',
                        'rating' => 4.8,
                    ],
                    [
                        'name' => 'Mercato di Mezzo',
                        'description' => 'Stunning food market in a medieval portico arcade. Perfect for sampling local cheeses, charcuterie, and wine.',
                        'cuisine' => 'Market & Food Hall',
                        'price_range' => '$$',
                        'address' => 'Via Clavature 12, Bologna',
                        'rating' => 4.6,
                    ],
                ],
                'best_time' => 'April - June, September - October',
                'budget' => '$$',
                'language' => 'Italian',
                'currency' => 'Euro (EUR)',
                'travel_tips' => 'Never order "spaghetti bolognese" — it doesn\'t exist here! The proper dish is tagliatelle al ragù. Visit FICO Eataly World, the world\'s largest food theme park. Take a cooking class to learn handmade pasta.',
                'is_featured' => false,
                'is_hidden_gem' => false,
                'rating' => 4.7,
                'meta_title' => 'Bologna Food Travel Guide — Italy\'s Culinary Capital',
                'meta_description' => 'Discover Bologna\'s food scene. Guide to traditional dishes, markets, cooking classes, and the best trattorias.',
            ],
            [
                'category_id' => $food->id,
                'name' => 'Oaxaca',
                'slug' => 'oaxaca-mexico',
                'location' => 'Oaxaca, Mexico',
                'description' => 'Oaxaca is Mexico\'s culinary treasure, home to seven legendary mole sauces — each one a complex symphony of chiles, spices, chocolate, and nuts that can take days to prepare. This colonial city in southern Mexico has become a global destination for food lovers seeking authentic, deeply rooted culinary traditions. The bustling Mercado Benito Juárez and Mercado 20 de Noviembre offer an immersive introduction to Oaxacan cuisine — from tlayudas (Oaxacan pizza) to chapulines (toasted grasshoppers) to steaming cups of hot chocolate made from locally grown cacao.',
                'short_description' => 'Mexico\'s culinary jewel — seven legendary moles, artisanal mezcal, and ancient Zapotec food traditions.',
                'latitude' => 17.0732,
                'longitude' => -96.7266,
                'hero_image' => 'images/destinations/oaxaca-1.jpg',
                'gallery' => [
                    'images/destinations/oaxaca-1.jpg',
                    'images/destinations/oaxaca-2.jpg',
                    'images/destinations/oaxaca-3.jpg',
                ],
                'food_dishes' => [
                    [
                        'name' => 'Mole Negro',
                        'description' => 'The king of all moles — a complex sauce of 30+ ingredients including chilhuacle negro, chocolate, and spices simmered for days.',
                        'image' => 'images/food/oaxaca-mole.jpg',
                        'price_range' => '90–180 MXN',
                    ],
                    [
                        'name' => 'Tlayuda',
                        'description' => 'Oaxaca\'s answer to pizza — a crispy toasted corn flatbread topped with black beans, cheese, and Oaxacan meats.',
                        'image' => 'images/food/oaxaca-tlayuda.jpg',
                        'price_range' => '80–150 MXN',
                    ],
                    [
                        'name' => 'Artisanal Mezcal',
                        'description' => 'Oaxaca is the world capital of mezcal. Sample smoky, complex spirits from single-village distilleries.',
                        'image' => 'images/food/oaxaca-mezcal.jpg',
                        'price_range' => '80–300 MXN (per pour)',
                    ],
                ],
                'restaurants' => [
                    [
                        'name' => 'Los Danzantes',
                        'description' => 'Modern Oaxacan cuisine in a beautiful courtyard garden. Famous for innovative mole preparations and mezcal cocktails.',
                        'cuisine' => 'Contemporary Oaxacan',
                        'price_range' => '$$$',
                        'address' => 'Macedonio Alcalá 403, Oaxaca',
                        'rating' => 4.8,
                    ],
                    [
                        'name' => 'Casa Oaxaca El Restaurante',
                        'description' => 'Chef Alejandro Ruiz\'s landmark restaurant. Traditional recipes reimagined with local seasonal ingredients.',
                        'cuisine' => 'Modern Mexican',
                        'price_range' => '$$$',
                        'address' => 'García Vigil 407, Oaxaca',
                        'rating' => 4.9,
                    ],
                    [
                        'name' => 'Mercado 20 de Noviembre',
                        'description' => 'The most authentic Oaxacan food experience. Smoke-filled market stalls grilling tasajo, chorizo, and chicken over coals.',
                        'cuisine' => 'Traditional Oaxacan Market',
                        'price_range' => '$',
                        'address' => '20 de Noviembre s/n, Oaxaca Centro',
                        'rating' => 4.7,
                    ],
                ],
                'best_time' => 'October - April',
                'budget' => '$',
                'language' => 'Spanish, Zapotec',
                'currency' => 'Mexican Peso (MXN)',
                'travel_tips' => 'Visit during Guelaguetza festival (July) for cultural immersion. Try all seven moles. Take a mezcal distillery tour in nearby Matatlán. Markets are best visited in the morning.',
                'is_featured' => false,
                'is_hidden_gem' => true,
                'rating' => 4.8,
                'meta_title' => 'Oaxaca Food Travel Guide — Mole, Mezcal & Markets',
                'meta_description' => 'Explore Oaxaca\'s legendary food scene. Guide to mole varieties, mezcal tours, traditional markets, and cooking classes.',
            ],
            // ─── Pakistan ────────────────────────────────────────────────
            [
                'category_id' => $adventure->id,
                'name' => 'Hunza Valley',
                'slug' => 'hunza-valley-pakistan',
                'location' => 'Gilgit-Baltistan, Pakistan',
                'description' => 'Hunza Valley is one of the most breathtaking mountain valleys on Earth, nestled among the Karakoram Range in the far north of Pakistan. Surrounded by five peaks over 7,000 meters — including the iconic Rakaposhi (7,788m), Ultar Sar (7,388m), and Diran — the valley sits at an elevation of 2,500 meters and has captivated explorers and travellers for centuries. The ancient Baltit Fort, perched dramatically above Karimabad town, has guarded the valley for 700 years and offers panoramic views across the glaciers and apricot orchards below. Hunza is famous for the legendary longevity of its people, traditionally attributed to a diet rich in apricots, mulberries, almonds, and glacial spring water. In spring, the valley erupts in a blizzard of pink and white blossom as thousands of apricot trees flower simultaneously against a backdrop of snow-capped peaks — creating one of the most stunning natural spectacles in all of Asia. The Attabad Lake, formed by a catastrophic landslide in 2010, is now an ethereal turquoise jewel surrounded by stark grey cliffs, and is traversed by the famous Karakoram Highway — the highest paved international road in the world.',
                'short_description' => 'A mythical mountain kingdom of apricot orchards, ancient forts, and soaring Karakoram peaks touching the sky.',
                'latitude' => 36.3167,
                'longitude' => 74.6500,
                'hero_image' => 'images/destinations/hunza-1.jpg',
                'gallery' => [
                    'images/destinations/hunza-1.jpg',
                    'images/destinations/hunza-2.jpg',
                    'images/destinations/hunza-3.jpg',
                ],
                'best_time' => 'April - October',
                'budget' => '$',
                'language' => 'Burushaski, Urdu, English',
                'currency' => 'Pakistani Rupee (PKR)',
                'travel_tips' => 'April brings magical apricot blossom — book accommodation months ahead. The Karakoram Highway (KKH) is scenic but requires a sturdy vehicle. Visit Baltit and Altit forts. Try fresh apricot juice, walnut cake, and chapshuro (Hunza meat pie). Acclimatize before attempting high-altitude treks.',
                'food_dishes' => [
                    [
                        'name' => 'Chapshuro',
                        'description' => 'The Hunza version of a meat pie, filled with minced beef, sheep, or yak meat, seasoned with local herbs and baked.',
                        'image' => 'images/food/default.jpg',
                        'price_range' => '300-500 PKR',
                    ],
                    [
                        'name' => 'Diram Fiti',
                        'description' => 'A sweet bread made from sprouted wheat, baked slowly, and traditionally served with almond or apricot oil.',
                        'image' => 'images/food/default.jpg',
                        'price_range' => '200-400 PKR',
                    ],
                    [
                        'name' => 'Harissa',
                        'description' => 'A hearty and ancient dish made from wheat, meat, and oil, cooked slowly until it becomes a rich paste.',
                        'image' => 'images/food/default.jpg',
                        'price_range' => '400-700 PKR',
                    ]
                ],
                'restaurants' => [
                    [
                        'name' => 'Hidden Paradise Hunza',
                        'description' => 'Famous for serving authentic traditional Hunza dishes like Chapshuro and Dawdo soup in a beautiful setting.',
                        'cuisine' => 'Traditional Hunza Food',
                        'price_range' => '$$',
                        'address' => 'Karimabad, Hunza',
                        'rating' => 4.8,
                    ],
                    [
                        'name' => 'Glacier View Restaurant',
                        'description' => 'Offers stunning panoramic views of the Rakaposhi and Ultar Sar peaks alongside excellent local and Pakistani cuisine.',
                        'cuisine' => 'Pakistani & Local',
                        'price_range' => '$$$',
                        'address' => 'Eagle\'s Nest, Duikar',
                        'rating' => 4.7,
                    ]
                ],
                'is_featured' => true,
                'is_hidden_gem' => false,
                'rating' => 4.9,
                'meta_title' => 'Hunza Valley Travel Guide — Karakoram Mountains, Pakistan',
                'meta_description' => 'Plan your Hunza Valley trip. Complete guide to Baltit Fort, Attabad Lake, apricot blossom season, Karakoram Highway, and high-altitude trekking.',
            ],
            [
                'category_id' => $adventure->id,
                'name' => 'Swat Valley',
                'slug' => 'swat-valley-pakistan',
                'location' => 'Khyber Pakhtunkhwa, Pakistan',
                'description' => 'Swat Valley, long known as the "Switzerland of Pakistan," is a verdant paradise of emerald-green meadows, crystal-clear rivers, lush pine forests, and snow-capped peaks in the Hindu Kush range of northwestern Pakistan. The Swat River flows through its heart, carving a lush corridor through granite mountains that have been inhabited for over 3,000 years. The valley\'s rich history as the ancient kingdom of Uddiyana makes it a treasure trove of Gandharan Buddhist art and archaeology — Swat was once the most important Buddhist centre in the ancient world, and hundreds of rock carvings, stupas, and ruins dot the mountainsides. Malam Jabba ski resort, nestled at 2,804 meters, offers the finest skiing in Pakistan. The Mahodand Lake, a glacial alpine lake at 3,050 meters, glimmers beneath snowfields and wildflower meadows, accessible via a dramatic jeep track through Ushu forest — one of the most beautiful drives in South Asia. Kalam, the gateway to the upper valley, is a charming town of wooden hotels perched above roaring rivers, beloved by Pakistani families in summer and thrill-seeking trekkers year-round.',
                'short_description' => 'The Switzerland of Pakistan — emerald valleys, Buddhist ruins, ski slopes, and glacial lakes in the Hindu Kush.',
                'latitude' => 35.2227,
                'longitude' => 72.4258,
                'hero_image' => 'images/destinations/swat-1.jpg',
                'gallery' => [
                    'images/destinations/swat-1.jpg',
                    'images/destinations/swat-2.jpg',
                    'images/destinations/swat-3.jpg',
                ],
                'best_time' => 'May - September',
                'budget' => '$',
                'language' => 'Pashto, Urdu',
                'currency' => 'Pakistani Rupee (PKR)',
                'travel_tips' => 'Visit Mahodand Lake in summer for wildflowers and horse riding. Ski at Malam Jabba from December to March. Explore Buddhist stupas at Butkara and Udegram. Kalam is a great base for upper-valley treks. Book a local guide for jeep safaris to remote meadows.',
                'food_dishes' => [
                    [
                        'name' => 'Lamb Karahi',
                        'description' => 'A beautifully spiced and fragrant lamb dish cooked in a wok (karahi) with tomatoes, ginger, and green chilies.',
                        'image' => 'images/food/default.jpg',
                        'price_range' => '1500-2500 PKR',
                    ],
                    [
                        'name' => 'Chapli Kebab',
                        'description' => 'A flat and round minced meat patty, spiced heavily with local ingredients and deep-fried to perfection.',
                        'image' => 'images/food/default.jpg',
                        'price_range' => '300-600 PKR',
                    ]
                ],
                'restaurants' => [
                    [
                        'name' => 'Swat Serena Hotel Restaurant',
                        'description' => 'Upscale dining set in gorgeous gardens, offering fine Pakistani cuisine and continental dishes with legendary Swati hospitality.',
                        'cuisine' => 'Fine Pakistani Dining',
                        'price_range' => '$$$',
                        'address' => 'Saidu Sharif, Swat',
                        'rating' => 4.8,
                    ]
                ],
                'is_featured' => true,
                'is_hidden_gem' => false,
                'rating' => 4.8,
                'meta_title' => 'Swat Valley Travel Guide — The Switzerland of Pakistan',
                'meta_description' => 'Explore Swat Valley, Pakistan. Guide to Malam Jabba ski resort, Kalam, Mahodand Lake, Buddhist ruins, and adventure trekking.',
            ],
            [
                'category_id' => $adventure->id,
                'name' => 'Gilgit-Baltistan',
                'slug' => 'gilgit-baltistan-pakistan',
                'location' => 'Gilgit-Baltistan, Pakistan',
                'description' => 'Gilgit-Baltistan is the crown jewel of Pakistan\'s north — a vast, awe-inspiring territory where three of the world\'s greatest mountain ranges converge: the Karakoram, the Himalayas, and the Hindu Kush. This is one of the most dramatically beautiful regions on Earth, home to four of the world\'s fourteen 8,000-metre peaks including the savage K2 (8,611m) — the world\'s second-highest and most technically demanding mountain. Fairy Meadows, a lush alpine plateau at 3,300 meters, sits directly at the foot of Nanga Parbat (8,126m) — the infamous "Killer Mountain" — offering one of the most surreal mountain views on the planet. The Deosai National Park, one of the world\'s highest plateaus at an average elevation of 4,114 meters, bursts with wildflowers every July and is home to the critically endangered Himalayan brown bear. The ancient Silk Road passed through Gilgit, leaving behind an extraordinary collection of Buddhist rock carvings, petroglyphs, and historical monuments spanning 5,000 years of continuous human habitation. Skardu, the regional capital of Baltistan, serves as the base camp for K2 and Broad Peak expeditions and hosts a thriving adventure tourism industry.',
                'short_description' => 'Where three great mountain ranges meet — K2, Nanga Parbat, Fairy Meadows, and the world\'s highest adventure playground.',
                'latitude' => 35.8026,
                'longitude' => 74.9826,
                'hero_image' => 'images/destinations/gilgit-1.jpg',
                'gallery' => [
                    'images/destinations/gilgit-1.jpg',
                    'images/destinations/gilgit-2.jpg',
                    'images/destinations/gilgit-3.jpg',
                ],
                'best_time' => 'June - September',
                'budget' => '$',
                'language' => 'Balti, Shina, Urdu, English',
                'currency' => 'Pakistani Rupee (PKR)',
                'travel_tips' => 'Permits are required for K2 base camp trekking — arrange through a licensed agency. Fly Islamabad–Skardu for a spectacular aerial view of the Karakoram. Fairy Meadows requires a 3-hour jeep ride and 2-hour hike. Deosai is best in July for flowers and bear sightings. Acclimatize properly before high-altitude excursions.',
                'food_dishes' => [
                    [
                        'name' => 'Mamtu',
                        'description' => 'Steamed dumplings filled with minced meat, onions, and herbs, a popular snack across Gilgit-Baltistan.',
                        'image' => 'images/food/default.jpg',
                        'price_range' => '400-700 PKR',
                    ],
                    [
                        'name' => 'Skardu Trout',
                        'description' => 'Fresh river trout caught directly from the icy mountain streams, lightly fried or grilled with mild seasoning.',
                        'image' => 'images/food/default.jpg',
                        'price_range' => '1000-2000 PKR',
                    ],
                    [
                        'name' => 'Marzan',
                        'description' => 'A traditional dish made with buckwheat flour dough served with apricot oil, usually prepared for special occasions.',
                        'image' => 'images/food/default.jpg',
                        'price_range' => '500-900 PKR',
                    ]
                ],
                'restaurants' => [
                    [
                        'name' => 'Dewan-E-Khas',
                        'description' => 'One of Skardu\'s most famous dining spots, known for its excellent Balti food and local specialties.',
                        'cuisine' => 'Balti & Pakistani',
                        'price_range' => '$$',
                        'address' => 'Skardu City',
                        'rating' => 4.6,
                    ]
                ],
                'is_featured' => true,
                'is_hidden_gem' => false,
                'rating' => 4.9,
                'meta_title' => 'Gilgit-Baltistan Travel Guide — K2, Fairy Meadows & Pakistan Karakoram',
                'meta_description' => 'Discover Gilgit-Baltistan, Pakistan. Guide to K2 base camp, Fairy Meadows, Deosai Plateau, Skardu, and the world\'s highest adventure treks.',
            ],
            [
                'category_id' => $food->id,
                'name' => 'George Town',
                'slug' => 'george-town-penang',
                'location' => 'Penang, Malaysia',
                'description' => 'George Town, the capital of Penang island, is a UNESCO World Heritage Site that doubles as one of Southeast Asia\'s greatest food destinations. The city\'s unique cultural mix — Malay, Chinese, Indian, and Peranakan — has created one of the world\'s most diverse and delicious street food scenes. Hawker centers like Gurney Drive and New Lane buzz with activity from morning until late night, offering an astonishing variety of dishes. The city is also known for its stunning street art, colonial architecture, and Chinese clan jetties.',
                'short_description' => 'A UNESCO heritage food paradise — where Malay, Chinese, and Indian flavors create an extraordinary fusion.',
                'latitude' => 5.4141,
                'longitude' => 100.3288,
                'hero_image' => 'images/destinations/penang-1.jpg',
                'gallery' => [
                    'images/destinations/penang-1.jpg',
                    'images/destinations/penang-2.jpg',
                    'images/destinations/penang-3.jpg',
                ],
                'food_dishes' => [
                    [
                        'name' => 'Char Kway Teow',
                        'description' => 'Penang\'s most famous dish — flat rice noodles stir-fried in a scorching wok with cockles, Chinese sausage, and bean sprouts.',
                        'image' => 'images/food/penang-char-kway-teow.jpg',
                        'price_range' => '8–15 MYR',
                    ],
                    [
                        'name' => 'Penang Assam Laksa',
                        'description' => 'Ranked among the world\'s best foods by CNN — a tangy tamarind-based fish soup with thick noodles and pineapple.',
                        'image' => 'images/food/penang-laksa.jpg',
                        'price_range' => '7–12 MYR',
                    ],
                    [
                        'name' => 'Nasi Kandar',
                        'description' => 'Penang\'s legendary rice dish — steamed rice loaded with curries, fried chicken, and a dozen condiments.',
                        'image' => 'images/food/penang-hawker.jpg',
                        'price_range' => '10–20 MYR',
                    ],
                ],
                'restaurants' => [
                    [
                        'name' => 'Lorong Selamat Char Kway Teow',
                        'description' => 'The most famous char kway teow stall in Penang. Run by the same family for generations. Queue up early.',
                        'cuisine' => 'Penang Street Food',
                        'price_range' => '$',
                        'address' => 'Lorong Selamat, George Town, Penang',
                        'rating' => 4.9,
                    ],
                    [
                        'name' => 'Line Clear Nasi Kandar',
                        'description' => '24-hour institution for nasi kandar since 1930. Beloved by locals, rock stars, and prime ministers alike.',
                        'cuisine' => 'Nasi Kandar',
                        'price_range' => '$',
                        'address' => 'Penang Road, George Town',
                        'rating' => 4.7,
                    ],
                    [
                        'name' => 'Kebaya',
                        'description' => 'Refined Peranakan cuisine in a stunning colonial heritage mansion. Celebrates the unique Straits Chinese culinary tradition.',
                        'cuisine' => 'Peranakan Fine Dining',
                        'price_range' => '$$$',
                        'address' => 'Seven Terraces Hotel, Stewart Lane, George Town',
                        'rating' => 4.8,
                    ],
                ],
                'best_time' => 'December - March',
                'budget' => '$',
                'language' => 'Malay, English, Chinese dialects',
                'currency' => 'Malaysian Ringgit (MYR)',
                'travel_tips' => 'Must-try: char kway teow, assam laksa, nasi kandar, cendol. Each hawker stall specializes in one dish — don\'t order off-menu. Eat at stalls with longest queues.',
                'is_featured' => false,
                'is_hidden_gem' => true,
                'rating' => 4.6,
                'meta_title' => 'George Town Penang Food Guide — Street Food & Hawker Culture',
                'meta_description' => 'Discover Penang\'s legendary food scene. Guide to hawker centers, must-try dishes, and the best food trails in George Town.',
            ],
        ];

        foreach ($destinations as $destination) {
            Destination::updateOrCreate(['slug' => $destination['slug']], $destination);
        }
    }
}
