<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Destination;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $adventure = Category::where('slug', 'adventure')->first();
        $culture = Category::where('slug', 'culture')->first();
        $food = Category::where('slug', 'food')->first();

        $destinations = [
            // Adventure
            [
                'category_id' => $adventure->id,
                'name' => 'Patagonia',
                'slug' => 'patagonia-chile',
                'location' => 'Torres del Paine, Chile',
                'description' => 'Patagonia is a sparsely populated region at the southern end of South America, shared by Argentina and Chile. The region comprises the southern section of the Andes mountains, lakes, fjords, and glaciers. The iconic Torres del Paine granite peaks rise dramatically above the landscape, creating one of the most spectacular mountain vistas on Earth. Trekkers from around the world come to experience the famous W Trek and Circuit, navigating through ancient forests of lenga beech trees, crossing suspension bridges over turquoise rivers, and camping beneath star-filled southern skies. The region is home to guanacos, condors, and pumas that roam the vast grasslands.',
                'short_description' => 'Embark on epic treks through glaciers, granite towers, and pristine wilderness in South America\'s last frontier.',
                'latitude' => -51.2538,
                'longitude' => -72.3464,
                'hero_image' => 'images/destinations/patagonia.jpg',
                'gallery' => ['images/destinations/patagonia.jpg', 'images/destinations/patagonia.jpg', 'images/destinations/patagonia.jpg'],
                'best_time' => 'October - April',
                'budget' => '$$$',
                'language' => 'Spanish',
                'currency' => 'Chilean Peso (CLP)',
                'travel_tips' => 'Book refugios (mountain huts) well in advance for the W Trek. Bring layers — weather changes rapidly. Wind-proof gear is essential. Park entrance fees apply.',
                'is_featured' => true,
                'is_hidden_gem' => false,
                'rating' => 4.9,
                'meta_title' => 'Patagonia Travel Guide — Trek Torres del Paine, Chile',
                'meta_description' => 'Plan your Patagonia adventure. Comprehensive guide to trekking Torres del Paine, including best trails, packing tips, and booking advice.',
            ],
            [
                'category_id' => $adventure->id,
                'name' => 'Banff National Park',
                'slug' => 'banff-national-park',
                'location' => 'Alberta, Canada',
                'description' => 'Banff National Park, established in 1885, is Canada\'s oldest national park and part of the Canadian Rocky Mountain Parks UNESCO World Heritage Site. Spanning over 6,641 square kilometers of mountainous terrain, the park is home to some of the most breathtaking alpine scenery in the world. Lake Louise, with its emerald-green waters reflecting the surrounding glaciers and mountains, is one of the most photographed lakes on Earth. The Icefields Parkway connects Banff to Jasper, offering 232 kilometers of awe-inspiring mountain vistas, ancient glaciers, and cascading waterfalls.',
                'short_description' => 'Crystal-clear alpine lakes, towering peaks, and world-class skiing in the heart of the Canadian Rockies.',
                'latitude' => 51.4968,
                'longitude' => -115.9281,
                'hero_image' => 'images/destinations/banff.jpg',
                'gallery' => ['images/destinations/banff.jpg', 'images/destinations/banff.jpg', 'images/destinations/banff.jpg'],
                'best_time' => 'June - September',
                'budget' => '$$',
                'language' => 'English, French',
                'currency' => 'Canadian Dollar (CAD)',
                'travel_tips' => 'Get a Parks Canada Discovery Pass for best value. Book Lake Louise parking shuttle in summer. Watch for wildlife on roads. Carry bear spray on hikes.',
                'is_featured' => true,
                'is_hidden_gem' => false,
                'rating' => 4.8,
                'meta_title' => 'Banff National Park Travel Guide — Canadian Rockies Adventure',
                'meta_description' => 'Explore Banff National Park. Guide to hiking, Lake Louise, Icefields Parkway, wildlife, and seasonal tips.',
            ],
            [
                'category_id' => $adventure->id,
                'name' => 'Queenstown',
                'slug' => 'queenstown-new-zealand',
                'location' => 'Otago, New Zealand',
                'description' => 'Nestled on the shores of Lake Wakatipu and surrounded by the Remarkables mountain range, Queenstown is widely regarded as the adventure capital of the world. This compact town packs an extraordinary range of adrenaline-pumping activities into its stunning alpine setting. From bungee jumping at the historic Kawarau Bridge — the world\'s first commercial bungee site — to jet boating through narrow canyons at breathtaking speeds, the options are limitless. In winter, four world-class ski fields transform the surrounding mountains into a paradise for snow sports enthusiasts.',
                'short_description' => 'The adventure capital of the world — bungee jumping, skydiving, and jaw-dropping alpine scenery.',
                'latitude' => -45.0312,
                'longitude' => 168.6626,
                'hero_image' => 'images/destinations/queenstown.jpg',
                'gallery' => ['images/destinations/queenstown.jpg', 'images/destinations/queenstown.jpg', 'images/destinations/queenstown.jpg'],
                'best_time' => 'December - February',
                'budget' => '$$',
                'language' => 'English',
                'currency' => 'New Zealand Dollar (NZD)',
                'travel_tips' => 'Book adventure activities online for discounts. The Queenstown Trail offers free scenic biking. Drive the Glenorchy Road for LOTR filming locations.',
                'is_featured' => false,
                'is_hidden_gem' => false,
                'rating' => 4.7,
                'meta_title' => 'Queenstown Travel Guide — New Zealand Adventure Capital',
                'meta_description' => 'Your guide to Queenstown, New Zealand. Best adventure activities, skiing, scenic drives, and travel tips.',
            ],
            [
                'category_id' => $adventure->id,
                'name' => 'Faroe Islands',
                'slug' => 'faroe-islands',
                'location' => 'North Atlantic, Denmark',
                'description' => 'The Faroe Islands are an archipelago of 18 volcanic islands in the North Atlantic, between Iceland and Norway. These remote islands offer some of the most dramatic and untouched landscapes in Europe — sheer sea cliffs plunging hundreds of meters into the ocean, grass-roofed villages clinging to mountainsides, and cascading waterfalls that seem to flow directly into the sea. The famous Múlafossur Waterfall in Gásadalur village drops 30 meters from a cliff edge directly into the ocean, creating one of the most iconic scenes in world travel.',
                'short_description' => 'Remote volcanic islands with dramatic sea cliffs, grass-roofed villages, and waterfalls cascading into the ocean.',
                'latitude' => 61.8926,
                'longitude' => -6.9118,
                'hero_image' => 'images/destinations/faroe.jpg',
                'gallery' => ['images/destinations/faroe.jpg', 'images/destinations/faroe.jpg', 'images/destinations/faroe.jpg'],
                'best_time' => 'May - September',
                'budget' => '$$$',
                'language' => 'Faroese, Danish',
                'currency' => 'Danish Krone (DKK)',
                'travel_tips' => 'Rent a car — public transport is limited. Weather changes every 15 minutes. Pack waterproof everything. Try fermented lamb and fresh seafood.',
                'is_featured' => false,
                'is_hidden_gem' => true,
                'rating' => 4.9,
                'meta_title' => 'Faroe Islands Travel Guide — Remote North Atlantic Adventure',
                'meta_description' => 'Discover the Faroe Islands. Guide to dramatic cliffs, hidden villages, hiking trails, and travel essentials.',
            ],

            // Culture
            [
                'category_id' => $culture->id,
                'name' => 'Kyoto',
                'slug' => 'kyoto-japan',
                'location' => 'Kansai, Japan',
                'description' => 'Kyoto served as Japan\'s capital for over a thousand years, from 794 to 1868, and remains the country\'s cultural heart. The city is home to an extraordinary 17 UNESCO World Heritage Sites, over 2,000 temples and shrines, and a living tradition of arts and crafts that stretches back centuries. Walking through the vermillion torii gates of Fushimi Inari Shrine, watching a geisha glide through the lantern-lit streets of Gion, or contemplating the perfect simplicity of a Zen rock garden — these are experiences that connect visitors to the deep spiritual and aesthetic traditions of Japan.',
                'short_description' => 'Ancient temples, bamboo forests, and geisha districts — the timeless cultural heart of Japan.',
                'latitude' => 35.0116,
                'longitude' => 135.7681,
                'hero_image' => 'images/destinations/kyoto.jpg',
                'gallery' => ['images/destinations/kyoto.jpg', 'images/destinations/kyoto.jpg', 'images/destinations/kyoto.jpg'],
                'best_time' => 'March - May, October - November',
                'budget' => '$$',
                'language' => 'Japanese',
                'currency' => 'Japanese Yen (JPY)',
                'travel_tips' => 'Visit Fushimi Inari at dawn to avoid crowds. Get a bus day pass for ¥700. Cherry blossom season (late March) and autumn foliage (November) are peak — book months ahead.',
                'is_featured' => true,
                'is_hidden_gem' => false,
                'rating' => 4.9,
                'meta_title' => 'Kyoto Travel Guide — Temples, Geisha & Japanese Culture',
                'meta_description' => 'Explore Kyoto, Japan. Complete guide to temples, shrines, traditional culture, cherry blossoms, and local cuisine.',
            ],
            [
                'category_id' => $culture->id,
                'name' => 'Machu Picchu',
                'slug' => 'machu-picchu-peru',
                'location' => 'Cusco Region, Peru',
                'description' => 'Perched at 2,430 meters above sea level on a mountain ridge above the Sacred Valley, Machu Picchu is the most iconic archaeological site in the Americas. Built in the 15th century under the Inca emperor Pachacuti, this extraordinary citadel was abandoned during the Spanish Conquest and remained hidden from the outside world until American explorer Hiram Bingham brought it to international attention in 1911. The site\'s sophisticated dry-stone construction, astronomical alignments, and terraced agricultural design demonstrate the remarkable engineering prowess of the Inca civilization.',
                'short_description' => 'The legendary lost city of the Incas — a mountaintop citadel of extraordinary archaeological wonder.',
                'latitude' => -13.1631,
                'longitude' => -72.5450,
                'hero_image' => 'images/destinations/machu-picchu.jpg',
                'gallery' => ['images/destinations/machu-picchu.jpg', 'images/destinations/machu-picchu.jpg', 'images/destinations/machu-picchu.jpg'],
                'best_time' => 'April - October',
                'budget' => '$$',
                'language' => 'Spanish, Quechua',
                'currency' => 'Peruvian Sol (PEN)',
                'travel_tips' => 'Book Inca Trail permits 6+ months ahead — only 500 people per day. Acclimatize in Cusco (3,400m) for 2-3 days first. Arrive at dawn for the best photos and fewer crowds.',
                'is_featured' => true,
                'is_hidden_gem' => false,
                'rating' => 4.9,
                'meta_title' => 'Machu Picchu Travel Guide — Inca Trail & Ancient Citadel',
                'meta_description' => 'Plan your Machu Picchu trip. Guide to the Inca Trail, permits, altitude tips, and exploring the Sacred Valley.',
            ],
            [
                'category_id' => $culture->id,
                'name' => 'Fez Medina',
                'slug' => 'fez-medina-morocco',
                'location' => 'Fez, Morocco',
                'description' => 'Fez el-Bali is the largest car-free urban area in the world and one of the best-preserved medieval cities on Earth. Founded in the 9th century, the medina contains over 9,000 alleyways — some so narrow that only a donkey can pass through. Within this labyrinthine maze lies the University of al-Qarawiyyin, founded in 859 AD and recognized by UNESCO as the oldest existing, continually operating university in the world. The Chouara Tannery, where leather has been dyed using traditional methods for nearly a thousand years, offers one of Morocco\'s most iconic visual experiences.',
                'short_description' => 'The world\'s largest car-free urban area — a living medieval labyrinth of artisans, spices, and ancient learning.',
                'latitude' => 34.0617,
                'longitude' => -4.9734,
                'hero_image' => 'images/destinations/fez.jpg',
                'gallery' => ['images/destinations/fez.jpg', 'images/destinations/fez.jpg', 'images/destinations/fez.jpg'],
                'best_time' => 'March - May, September - November',
                'budget' => '$',
                'language' => 'Arabic, French, Berber',
                'currency' => 'Moroccan Dirham (MAD)',
                'travel_tips' => 'Hire an official guide for your first medina visit — it\'s easy to get lost. Visit tanneries in the morning when colors are being prepared. Bargain respectfully at souks — start at 40% of asking price.',
                'is_featured' => false,
                'is_hidden_gem' => true,
                'rating' => 4.6,
                'meta_title' => 'Fez Medina Travel Guide — Morocco\'s Ancient Labyrinth',
                'meta_description' => 'Discover Fez Medina, Morocco. Guide to navigating the ancient medina, tanneries, artisan workshops, and Moroccan cuisine.',
            ],
            [
                'category_id' => $culture->id,
                'name' => 'Valletta',
                'slug' => 'valletta-malta',
                'location' => 'Malta',
                'description' => 'Valletta, the capital of Malta, is a UNESCO World Heritage Site and one of the most concentrated historic areas in the world. Built by the Knights of St. John after the Great Siege of 1565, every street in this tiny capital (measuring just 1km by 600m) is a masterpiece of Baroque architecture. St. John\'s Co-Cathedral houses Caravaggio\'s masterpiece "The Beheading of Saint John the Baptist." The city sits on a peninsula surrounded by the Grand Harbour, offering stunning views at every turn. Despite its small size, Valletta packs more history per square meter than almost any city on Earth.',
                'short_description' => 'A Baroque masterpiece — Europe\'s smallest capital packed with Knights Templar history and Mediterranean charm.',
                'latitude' => 35.8989,
                'longitude' => 14.5146,
                'hero_image' => 'images/destinations/valletta.jpg',
                'gallery' => ['images/destinations/valletta.jpg', 'images/destinations/valletta.jpg', 'images/destinations/valletta.jpg'],
                'best_time' => 'April - June, September - November',
                'budget' => '$$',
                'language' => 'Maltese, English',
                'currency' => 'Euro (EUR)',
                'travel_tips' => 'Walk everywhere — Valletta is tiny and best explored on foot. Visit the Upper Barrakka Gardens at noon for the cannon salute. Take a harbor cruise for the best views of the city\'s fortifications.',
                'is_featured' => false,
                'is_hidden_gem' => true,
                'rating' => 4.5,
                'meta_title' => 'Valletta Travel Guide — Malta\'s Baroque Capital',
                'meta_description' => 'Explore Valletta, Malta. Guide to Baroque architecture, Knights\' history, Mediterranean cuisine, and harbor views.',
            ],

            // Food
            [
                'category_id' => $food->id,
                'name' => 'Bangkok Street Food',
                'slug' => 'bangkok-street-food',
                'location' => 'Bangkok, Thailand',
                'description' => 'Bangkok is widely regarded as the street food capital of the world. The city\'s sidewalks, alleyways, and floating markets transform into an endless culinary landscape where the aroma of sizzling woks, grilling satay, and fragrant curries fills the air from dawn until well past midnight. Yaowarat Road in Chinatown comes alive after dark with hundreds of vendors offering everything from crispy pork belly to flambéed seafood. Jay Fai, a legendary street cook famous for her signature crab omelette, became the first Thai street food vendor to earn a Michelin star.',
                'short_description' => 'The world\'s street food capital — legendary night markets, Michelin-starred vendors, and flavors that ignite the senses.',
                'latitude' => 13.7563,
                'longitude' => 100.5018,
                'hero_image' => 'images/destinations/bangkok.jpg',
                'gallery' => ['images/destinations/bangkok.jpg', 'images/destinations/bangkok.jpg', 'images/destinations/bangkok.jpg'],
                'best_time' => 'November - February',
                'budget' => '$',
                'language' => 'Thai',
                'currency' => 'Thai Baht (THB)',
                'travel_tips' => 'Eat where locals eat — long queues = great food. Yaowarat is best after 7pm. Try pad thai, som tum, mango sticky rice, and boat noodles. Carry small bills for street vendors.',
                'is_featured' => true,
                'is_hidden_gem' => false,
                'rating' => 4.8,
                'meta_title' => 'Bangkok Street Food Guide — Night Markets & Local Eats',
                'meta_description' => 'Your guide to Bangkok street food. Best night markets, must-try dishes, food tours, and insider tips.',
            ],
            [
                'category_id' => $food->id,
                'name' => 'Bologna',
                'slug' => 'bologna-italy',
                'location' => 'Emilia-Romagna, Italy',
                'description' => 'Bologna, nicknamed "La Grassa" (The Fat One) by Italians themselves, is the undisputed culinary capital of Italy. This medieval university city in the Emilia-Romagna region is the birthplace of many of Italy\'s most beloved foods: ragù alla bolognese, tortellini, tagliatelle, mortadella, and lasagne all originated here. The city\'s food markets and portico-lined streets offer an authentic Italian culinary experience far removed from tourist traps. The Quadrilatero market district, dating back to the Middle Ages, is a sensory feast of hanging prosciutto, wheels of Parmigiano-Reggiano, and barrels of aged balsamic vinegar.',
                'short_description' => 'Italy\'s culinary capital — birthplace of ragù, tortellini, and Parmigiano-Reggiano in medieval splendor.',
                'latitude' => 44.4949,
                'longitude' => 11.3426,
                'hero_image' => 'images/destinations/bologna.jpg',
                'gallery' => ['images/destinations/bologna.jpg', 'images/destinations/bologna.jpg', 'images/destinations/bologna.jpg'],
                'best_time' => 'April - June, September - October',
                'budget' => '$$',
                'language' => 'Italian',
                'currency' => 'Euro (EUR)',
                'travel_tips' => 'Never order "spaghetti bolognese" — it doesn\'t exist here! The proper dish is tagliatelle al ragù. Visit FICO Eataly World, the world\'s largest food theme park. Take a cooking class to learn handmade pasta.',
                'is_featured' => false,
                'is_hidden_gem' => false,
                'rating' => 4.7,
                'meta_title' => 'Bologna Food Travel Guide — Italy\'s Culinary Capital',
                'meta_description' => 'Discover Bologna\'s food scene. Guide to traditional dishes, markets, cooking classes, and the best trattorias.',
            ],
            [
                'category_id' => $food->id,
                'name' => 'Oaxaca',
                'slug' => 'oaxaca-mexico',
                'location' => 'Oaxaca, Mexico',
                'description' => 'Oaxaca is Mexico\'s culinary treasure, home to seven legendary mole sauces — each one a complex symphony of chiles, spices, chocolate, and nuts that can take days to prepare. This colonial city in southern Mexico has become a global destination for food lovers seeking authentic, deeply rooted culinary traditions. The bustling Mercado Benito Juárez and Mercado 20 de Noviembre offer an immersive introduction to Oaxacan cuisine — from tlayudas (Oaxacan pizza) to chapulines (toasted grasshoppers) to steaming cups of hot chocolate made from locally grown cacao.',
                'short_description' => 'Mexico\'s culinary jewel — seven legendary moles, artisanal mezcal, and ancient Zapotec food traditions.',
                'latitude' => 17.0732,
                'longitude' => -96.7266,
                'hero_image' => 'images/destinations/oaxaca.jpg',
                'gallery' => ['images/destinations/oaxaca.jpg', 'images/destinations/oaxaca.jpg', 'images/destinations/oaxaca.jpg'],
                'best_time' => 'October - April',
                'budget' => '$',
                'language' => 'Spanish, Zapotec',
                'currency' => 'Mexican Peso (MXN)',
                'travel_tips' => 'Visit during Guelaguetza festival (July) for cultural immersion. Try all seven moles. Take a mezcal distillery tour in nearby Matatlán. Markets are best visited in the morning.',
                'is_featured' => false,
                'is_hidden_gem' => true,
                'rating' => 4.8,
                'meta_title' => 'Oaxaca Food Travel Guide — Mole, Mezcal & Markets',
                'meta_description' => 'Explore Oaxaca\'s legendary food scene. Guide to mole varieties, mezcal tours, traditional markets, and cooking classes.',
            ],
            [
                'category_id' => $food->id,
                'name' => 'George Town',
                'slug' => 'george-town-penang',
                'location' => 'Penang, Malaysia',
                'description' => 'George Town, the capital of Penang island, is a UNESCO World Heritage Site that doubles as one of Southeast Asia\'s greatest food destinations. The city\'s unique cultural mix — Malay, Chinese, Indian, and Peranakan — has created one of the world\'s most diverse and delicious street food scenes. Hawker centers like Gurney Drive and New Lane buzz with activity from morning until late night, offering an astonishing variety of dishes. The city is also known for its stunning street art, colonial architecture, and Chinese clan jetties.',
                'short_description' => 'A UNESCO heritage food paradise — where Malay, Chinese, and Indian flavors create an extraordinary fusion.',
                'latitude' => 5.4141,
                'longitude' => 100.3288,
                'hero_image' => 'images/destinations/penang.jpg',
                'gallery' => ['images/destinations/penang.jpg', 'images/destinations/penang.jpg', 'images/destinations/penang.jpg'],
                'best_time' => 'December - March',
                'budget' => '$',
                'language' => 'Malay, English, Chinese dialects',
                'currency' => 'Malaysian Ringgit (MYR)',
                'travel_tips' => 'Must-try: char kway teow, assam laksa, nasi kandar, cendol. Each hawker stall specializes in one dish — don\'t order off-menu. Eat at stalls with longest queues.',
                'is_featured' => false,
                'is_hidden_gem' => true,
                'rating' => 4.6,
                'meta_title' => 'George Town Penang Food Guide — Street Food & Hawker Culture',
                'meta_description' => 'Discover Penang\'s legendary food scene. Guide to hawker centers, must-try dishes, and the best food trails in George Town.',
            ],
        ];

        foreach ($destinations as $destination) {
            Destination::updateOrCreate(['slug' => $destination['slug']], $destination);
        }
    }
}
